version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: contabilidadma
      MYSQL_USER: sergio
      MYSQL_PASSWORD: sergiopass
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://sergio:sergiopass@db:3306/contabilidadma

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: sergio
      PMA_PASSWORD: sergiopass
    depends_on:
      - db

volumes:
  db_data: