import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Contabilidadma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="flex">
        <aside className="w-64 h-screen bg-gray-800 text-white p-4">
          <h2 className="text-xl font-bold mb-6">Contabilidad Mario y abogados </h2>
          <nav className="space-y-2">
            <a href="/nacionalidades" className="block hover:bg-gray-700 p-2 rounded">Nacionalidades</a>
            <a href="/nacionalidadesOpciones" className="block hover:bg-gray-700 p-2 rounded">Nacionalidades por opción</a>
            <a href="/arraigos" className="block hover:bg-gray-700 p-2 rounded">Arraigos</a>
            {/* Agrega más enlaces según tu menú */}
          </nav>
        </aside>
        <main className="flex-1 p-6 bg-gray-100">{children}</main>
      </body>
    </html>

  );
}
