-- AlterTable
ALTER TABLE `arraigados` MODIFY `nombre` VARCHAR(191) NULL,
    MODIFY `primer_apellido` VARCHAR(191) NULL,
    MODIFY `segundo_apellido` VARCHAR(191) NULL,
    MODIFY `telefono` VARCHAR(191) NULL,
    MODIFY `nacionalidad` VARCHAR(191) NULL,
    MODIFY `tipo_arraigado` VARCHAR(191) NULL,
    MODIFY `persona__arraigado` VARCHAR(191) NULL,
    MODIFY `lugar` VARCHAR(191) NULL,
    MODIFY `n_expediente` VARCHAR(191) NULL,
    MODIFY `fecha_presentacion` VARCHAR(191) NULL,
    MODIFY `saldo` INTEGER NULL,
    MODIFY `primer_pago` INTEGER NULL,
    MODIFY `segundo_pago` INTEGER NULL,
    MODIFY `tercer_pago` INTEGER NULL,
    MODIFY `saldo_restante` INTEGER NULL,
    MODIFY `notas` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `reagrupaciones` MODIFY `nombre` VARCHAR(191) NULL,
    MODIFY `primer_apellido` VARCHAR(191) NULL,
    MODIFY `segundo_apellido` VARCHAR(191) NULL,
    MODIFY `telefono` VARCHAR(191) NULL,
    MODIFY `nacionalidad` VARCHAR(191) NULL,
    MODIFY `tipo_reagrupacion` VARCHAR(191) NULL,
    MODIFY `persona_reagrupacion` VARCHAR(191) NULL,
    MODIFY `lugar` VARCHAR(191) NULL,
    MODIFY `n_expediente` VARCHAR(191) NULL,
    MODIFY `fecha_presentacion` VARCHAR(191) NULL,
    MODIFY `saldo` INTEGER NULL,
    MODIFY `primer_pago` INTEGER NULL,
    MODIFY `segundo_pago` INTEGER NULL,
    MODIFY `tercer_pago` INTEGER NULL,
    MODIFY `saldo_restante` INTEGER NULL,
    MODIFY `notas` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `renovaciones` MODIFY `nombre` VARCHAR(191) NULL,
    MODIFY `primer_apellido` VARCHAR(191) NULL,
    MODIFY `segundo_apellido` VARCHAR(191) NULL,
    MODIFY `telefono` VARCHAR(191) NULL,
    MODIFY `nacionalidad` VARCHAR(191) NULL,
    MODIFY `renovacion` VARCHAR(191) NULL,
    MODIFY `n_expediente` VARCHAR(191) NULL,
    MODIFY `fecha_presentacion` VARCHAR(191) NULL,
    MODIFY `saldo` INTEGER NULL,
    MODIFY `primer_pago` INTEGER NULL,
    MODIFY `segundo_pago` INTEGER NULL,
    MODIFY `tercer_pago` INTEGER NULL,
    MODIFY `saldo_restante` INTEGER NULL,
    MODIFY `notas` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `tarjetacomunitaria` MODIFY `nombre` VARCHAR(191) NULL,
    MODIFY `primer_apellido` VARCHAR(191) NULL,
    MODIFY `segundo_apellido` VARCHAR(191) NULL,
    MODIFY `telefono` VARCHAR(191) NULL,
    MODIFY `nacionalidad` VARCHAR(191) NULL,
    MODIFY `persona_reagrupacion` VARCHAR(191) NULL,
    MODIFY `n_expediente` VARCHAR(191) NULL,
    MODIFY `fecha_presentacion` VARCHAR(191) NULL,
    MODIFY `saldo` INTEGER NULL,
    MODIFY `primer_pago` INTEGER NULL,
    MODIFY `segundo_pago` INTEGER NULL,
    MODIFY `tercer_pago` INTEGER NULL,
    MODIFY `saldo_restante` INTEGER NULL,
    MODIFY `notas` VARCHAR(191) NULL;
